apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classroom-backend
  template:
    metadata:
      labels:
        app: classroom-backend
    spec:
      containers:
      - name: classroom-backend
        image: i211132usman/classroom-service:latest
        ports:
        - containerPort: 3133
        env:
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: classroom-backend
spec:
  selector:
    app: classroom-backend
  ports:
    - protocol: TCP
      port: 3133
      targetPort: 3133
  type: LoadBalancer
