apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventbus-backend
  template:
    metadata:
      labels:
        app: eventbus-backend
    spec:
      containers:
      - name: eventbus-backend
        image: i211132usman/eventbus-service:latest
        ports:
        - containerPort: 3139
        env:
        - name: MONGO_HOST
          value: "mu-mongodb-container"
        - name: MONGO_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: eventbus-backend
spec:
  selector:
    app: eventbus-backend
  ports:
    - protocol: TCP
      port: 3139
      targetPort: 3139
  type: LoadBalancer
